services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./services/init-db:/docker-entrypoint-initdb.d
    networks:
      - app-net

  # location-service:
  #   build:
  #     context: ./services/location/server
  #   ports:
  #     - "8082:8082"
  #   depends_on:
  #     - postgres
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     FIREBASE_CREDENTIAL: ${FIREBASE_CREDENTIAL}
  #   restart: unless-stopped
  #   networks:
  #     - app-net

  # diary-service:
  #   build:
  #     context: ./services/diary/server
  #   ports:
  #     - "8085:8085"
  #   depends_on:
  #     - postgres
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DIARY_DB: ${POSTGRES_DIARY_DB}
  #     FIREBASE_CREDENTIAL: ${FIREBASE_CREDENTIAL}
  #   restart: unless-stopped
  #   networks:
  #     - app-net

  asst-service:
    build:
      context: ./services/assistant/server
    ports:
      - "8086:8086"
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ASSISTANT_DB: ${POSTGRES_ASSISTANT_DB}
      FIREBASE_CREDENTIAL: ${FIREBASE_CREDENTIAL}
    restart: unless-stopped
    networks:
      - app-net

  analyze-service:
    build:
      context: ./services/analyze/server
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ASSISTANT_DB: ${POSTGRES_ANALYTIC_DB}
      FIREBASE_CREDENTIAL: ${FIREBASE_CREDENTIAL}
    restart: unless-stopped
    networks:
      - app-net

  # diary-ai-service:
  #   build:
  #     context: ./services/diary-ai
  #   ports:
  #     - "${AI_PORT:-8095}:${AI_PORT:-8095}"
  #   environment:
  #     GOOGLE_API_KEY: ${GOOGLE_API_KEY}
  #     LOG_LEVEL: ${LOG_LEVEL:-INFO}
  #     HOST: ${AI_HOST:-0.0.0.0}
  #     PORT: ${AI_PORT:-8095}
  #   restart: unless-stopped
  #   networks:
  #     - app-net

  asst-ai-service:
    build:
      context: ./services/assistant-ai
    ports:
      - "${ASST_AI_PORT:-8096}:${ASST_AI_PORT:-8096}"
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      HOST: ${AI_HOST:-0.0.0.0}
      PORT: ${ASST_AI_PORT:-8096}
    restart: unless-stopped
    networks:
      - app-net

  analytice-ai-service:
    build:
      context: ./services/analyze-ai
    ports:
      - "${ANALYTIC_AI_PORT:-8098}:${ANALYTIC_AI_PORT:-8098}"
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      HOST: ${AI_HOST:-0.0.0.0}
      PORT: ${ANALYTIC_AI_PORT:-8098}
    restart: unless-stopped
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
    driver: bridge
